//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEXMonitor
{
    using System;
    using System.Collections.Generic;
    
    public partial class HEX_Panels
    {
        public int id { get; set; }
        public long rp_id { get; set; }
        public Nullable<long> acc_id { get; set; }
        public string panel_name { get; set; }
        public Nullable<int> requisitions_id { get; set; }
        public string panel_id { get; set; }
    
        public virtual HEX_Requisitions HEX_Requisitions { get; set; }
    }
}
